### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by juliancoleman** [callemall/material-ui-webpack-example#7]
\> material-ui-example-webpack@0.16.4 start $HOME/material-ui-webpack-example
\> webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors

$HOME/material-ui-webpack-example/node_modules/webpack/lib/webpack.js:19
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

Error
    at webpack ($HOME/material-ui-webpack-example/node_modules/webpack/lib/webpack.js:19:9)
    at processOptions ($HOME/material-ui-webpack-example/node_modules/webpack-dev-server/bin/webpack-dev-server.js:209:13)
    at Object.<anonymous> ($HOME/material-ui-webpack-example/node_modules/webpack-dev-server/bin/webpack-dev-server.js:228:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

**Comment by oliviertassinari** [comment]
I have been running the following commands with no issue:
```sh
$ git clone git@github.com:callemall/material-ui-webpack-example.git
$ cd material-ui-webpack-example/
$ npm install
$ npm start
```

```sh
$ node -v
v7.2.0
$ npm -v
3.10.9
```

**Comment by juliancoleman** [comment]
Alright, let me try it again

**Comment by juliancoleman** [comment]
Okay, it looks like nvm decided to take a crap on this directory and use a super outdated version. This works now. Thank you!
